"""migrate_to_clerk

Revision ID: 51d6d6227432
Revises: 895ddd914ffb
Create Date: 2026-08-09 20:31:05.109451

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "51d6d6227432"
down_revision: str | None = "895ddd914ffb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("emailVerified", sa.Boolean(), nullable=False),
        sa.Column("image", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )

    op.alter_column(
        "analysis_jobs",
        "user_id",
        existing_type=sa.TEXT(),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("analysis_jobs_user_id_fkey"), "analysis_jobs", type_="foreignkey"
    )
    op.create_foreign_key(None, "analysis_jobs", "users", ["user_id"], ["id"])
    op.alter_column(
        "audit_logs",
        "user_id",
        existing_type=sa.TEXT(),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("audit_logs_user_id_fkey"), "audit_logs", type_="foreignkey"
    )
    op.create_foreign_key(None, "audit_logs", "users", ["user_id"], ["id"])
    op.alter_column(
        "commit_events",
        "user_id",
        existing_type=sa.TEXT(),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("commit_events_user_id_fkey"), "commit_events", type_="foreignkey"
    )
    op.create_foreign_key(None, "commit_events", "users", ["user_id"], ["id"])
    op.alter_column(
        "pr_drafts",
        "user_id",
        existing_type=sa.TEXT(),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.drop_constraint(op.f("pr_drafts_user_id_fkey"), "pr_drafts", type_="foreignkey")
    op.create_foreign_key(None, "pr_drafts", "users", ["user_id"], ["id"])
    op.alter_column(
        "repositories",
        "user_id",
        existing_type=sa.TEXT(),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("repositories_user_id_fkey"), "repositories", type_="foreignkey"
    )
    op.create_foreign_key(None, "repositories", "users", ["user_id"], ["id"])
    op.alter_column(
        "requirements",
        "user_id",
        existing_type=sa.TEXT(),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.drop_constraint(
        op.f("requirements_user_id_fkey"), "requirements", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "requirements", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_table("account")
    op.drop_table("session")
    op.drop_table("user")
    op.drop_table("verification")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "requirements", type_="foreignkey")
    op.create_foreign_key(
        op.f("requirements_user_id_fkey"),
        "requirements",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "requirements",
        "user_id",
        existing_type=sa.String(length=50),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "repositories", type_="foreignkey")
    op.create_foreign_key(
        op.f("repositories_user_id_fkey"), "repositories", "user", ["user_id"], ["id"]
    )
    op.alter_column(
        "repositories",
        "user_id",
        existing_type=sa.String(length=50),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "pr_drafts", type_="foreignkey")
    op.create_foreign_key(
        op.f("pr_drafts_user_id_fkey"), "pr_drafts", "user", ["user_id"], ["id"]
    )
    op.alter_column(
        "pr_drafts",
        "user_id",
        existing_type=sa.String(length=50),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "commit_events", type_="foreignkey")
    op.create_foreign_key(
        op.f("commit_events_user_id_fkey"), "commit_events", "user", ["user_id"], ["id"]
    )
    op.alter_column(
        "commit_events",
        "user_id",
        existing_type=sa.String(length=50),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "audit_logs", type_="foreignkey")
    op.create_foreign_key(
        op.f("audit_logs_user_id_fkey"), "audit_logs", "user", ["user_id"], ["id"]
    )
    op.alter_column(
        "audit_logs",
        "user_id",
        existing_type=sa.String(length=50),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "analysis_jobs", type_="foreignkey")
    op.create_foreign_key(
        op.f("analysis_jobs_user_id_fkey"), "analysis_jobs", "user", ["user_id"], ["id"]
    )
    op.alter_column(
        "analysis_jobs",
        "user_id",
        existing_type=sa.String(length=50),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.create_table(
        "account",
        sa.Column("id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("account_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("provider_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("access_token", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("refresh_token", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("id_token", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "access_token_expires_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "refresh_token_expires_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("scope", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("password", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("account_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("account_pkey")),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("email", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("email_verified", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("image", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_pkey")),
        sa.UniqueConstraint(
            "email",
            name=op.f("user_email_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "session",
        sa.Column("id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("token", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column("ip_address", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("user_agent", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("session_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("session_pkey")),
        sa.UniqueConstraint(
            "token",
            name=op.f("session_token_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "verification",
        sa.Column("id", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("identifier", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("value", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("verification_pkey")),
    )
    op.drop_table("users")
    # ### end Alembic commands ###
