"""Add github installation model

Revision ID: cfb6e3578b6f
Revises: 51d6d6227432
Create Date: 2026-08-12 22:55:12.168351

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cfb6e3578b6f"
down_revision: str | None = "51d6d6227432"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    conn = op.get_bind()
    conn.execute(
        sa.text(
            """
            CREATE TABLE IF NOT EXISTS github_installations (
                id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
                user_id VARCHAR(50) NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                installation_id INTEGER NOT NULL UNIQUE,
                account_name VARCHAR(255) NOT NULL,
                created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now(),
                updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT now()
            );
            """
        )
    )
    conn.execute(
        sa.text(
            "CREATE INDEX IF NOT EXISTS ix_github_installations_user_id ON github_installations (user_id);"
        )
    )
    conn.execute(
        sa.text(
            "ALTER TABLE repositories ADD COLUMN IF NOT EXISTS github_installation_id INTEGER NULL;"
        )
    )
    conn.execute(
        sa.text(
            "ALTER TABLE repositories ADD COLUMN IF NOT EXISTS is_private BOOLEAN NOT NULL DEFAULT false;"
        )
    )
    conn.execute(
        sa.text(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_constraint WHERE conname = 'fk_repositories_github_installation'
                ) THEN
                    ALTER TABLE repositories
                    ADD CONSTRAINT fk_repositories_github_installation
                    FOREIGN KEY (github_installation_id)
                    REFERENCES github_installations(installation_id)
                    ON DELETE SET NULL;
                END IF;
            END
            $$;
            """
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "repositories", type_="foreignkey")
    op.drop_column("repositories", "is_private")
    op.drop_column("repositories", "github_installation_id")
    op.drop_index(
        op.f("ix_github_installations_user_id"), table_name="github_installations"
    )
    op.drop_table("github_installations")
    # ### end Alembic commands ###
