"""Add github installation model

Revision ID: cfb6e3578b6f
Revises: 51d6d6227432
Create Date: 2026-08-12 22:55:12.168351

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cfb6e3578b6f'
down_revision: str | None = '51d6d6227432'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_installations',
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('installation_id')
    )
    op.create_index(op.f('ix_github_installations_user_id'), 'github_installations', ['user_id'], unique=False)
    op.add_column('repositories', sa.Column('github_installation_id', sa.Integer(), nullable=True))
    op.add_column('repositories', sa.Column('is_private', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_foreign_key(None, 'repositories', 'github_installations', ['github_installation_id'], ['installation_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repositories', type_='foreignkey')
    op.drop_column('repositories', 'is_private')
    op.drop_column('repositories', 'github_installation_id')
    op.drop_index(op.f('ix_github_installations_user_id'), table_name='github_installations')
    op.drop_table('github_installations')
    # ### end Alembic commands ###
